Add clang compilers to build matrix (#450)
* Add clang compilers to the build matrix

We need `-Wno-gnu-folding-constant` in order to fix the following error
with clang:

```
In file included from thapi_metadata_tracepoints.c:7:
In file included from ./thapi_metadata_tracepoints.h:26:
In file included from /home/thilina/share/spack/opt/spack/linux-icelake/lttng-ust-2.14.0-wlpfaxu7nrqtytdg3wrrpqr3gqwvmwah/include/lttng/tracepoint-event.h:67:
In file included from /home/thilina/share/spack/opt/spack/linux-icelake/lttng-ust-2.14.0-wlpfaxu7nrqtytdg3wrrpqr3gqwvmwah/include/lttng/ust-tracepoint-event.h:1064:
./thapi_metadata_tracepoints.h:13:1: error: variable length array folded to constant array as an extension [-Werror,-Wgnu-folding-constant]
   13 | TRACEPOINT_EVENT(
      | ^
/home/thilina/share/spack/opt/spack/linux-icelake/lttng-ust-2.14.0-wlpfaxu7nrqtytdg3wrrpqr3gqwvmwah/include/lttng/tracepoint.h:866:27: note: expanded from macro 'TRACEPOINT_EVENT'
  866 | #define TRACEPOINT_EVENT                LTTNG_UST_TRACEPOINT_EVENT
      |                                         ^
/home/thilina/share/spack/opt/spack/linux-icelake/lttng-ust-2.14.0-wlpfaxu7nrqtytdg3wrrpqr3gqwvmwah/include/lttng/ust-tracepoint-event.h:82:2: note: expanded from macro 'LTTNG_UST_TRACEPOINT_EVENT'
   82 |         LTTNG_UST__TRACEPOINT_EVENT_CLASS(_provider, _name,             \
      |         ^
/home/thilina/share/spack/opt/spack/linux-icelake/lttng-ust-2.14.0-wlpfaxu7nrqtytdg3wrrpqr3gqwvmwah/include/lttng/ust-tracepoint-event.h:974:10: note: expanded from macro 'LTTNG_UST__TRACEPOINT_EVENT_CLASS'
  974 |                 size_t __dynamic_len[__num_fields];
```

* Get rid of redundant checks for success

* Minor change in title